language: ruby
env: CUCUMBER_FORMAT=progress
bundler_args: --without extras
before_install: "echo 'Y' | gem uninstall json -a"
script: "script/ci.sh"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
    - 1-x-stable
    - travis-testing
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode

